version: 0.2

phases:
  install:
    commands:
      - apt-get -y update
      - apt-get -y install jq

  build:
    commands:
      - buildspecs/deploy.sh astrobin-app-launch-template astrobin-app-autoscaling-group 540
      - buildspecs/deploy.sh astrobin-scheduler-launch-template astrobin-scheduler-autoscaling-group 60
